while print("Var2 printed successfully") do
variable3 = true
variable4 = false
end


local variable1 = "Var1"
local variable2 = "Var2"

if print(variable1) then
    task.wait(5)
    print("Var1 printed successfully")
elseif print(variable2) then
    task.wait(5)
    print("Var2 printed successfully")
end

local function no()
    if print("Var1 printed successfully") then
        error("Chicken eaten")
            while true do
                warn("Fucking a chicken now")
            end
    end
end

if variable1 == nil then
    local variable1 = "Var1"
    local eaten = print("eaten")
    if eaten then
        print("Fuuuu")
        task.wait(5)
        local variable5 = variable3
        local variable6 = variable4
        eaten()
    end
end

no()
print(variable1)
print(variable2)

-- hmmm what the hell did i even think of while doing this?? 🙏