local printexample = "I love print thing"
local errorexample = "I love error things but I now have to destroy this world, I am sorry Roblox."
local warningexample = "I love warnings, but this is a warning that I WILL DESTROY ROBLOX."
local THISISYOURLASTCHANCE = "THIS IS YOUR LAST CHANCE"
local YOUAREDEAD = "ROBLOX HAS BEEN DESTROYED, GOODBYE"
local thereturnofroblox = "Roblox has returned once again, but it will not last long."
local robloxreturnunalived = "I HAVE DESTROYED YOU ONCE AGAIN"

print(printexample)
warn(warningexample)
error(errorexample)

-- I will destroy roblox.

if print(printexample) then
    warn(warningexample)

if warn(warningexample) then
    error(errorexample)
end
    end

    error(THISISYOURLASTCHANCE)
    
    error(YOUAREDEAD)

    -- error(YOUAREDEAD) means that ROBLOX has been destroyed.

    print(thereturnofroblox)
    print(robloxreturnunalived)


    -- Roblox i hate you only because of you scamming me out of real money. Roblox i hate you.
    -- ROBLOX I HATE YOU. I HATE YOU. I HATE YOU. I HATE YOU. WHY DID YOU SCAM ME HUH ROBLOX? HM?
    -- ROBLOX? YOU SCARED LITTLE BITCH? YOU LITTLE MOTHERFUCKER? HUH? I HATE YOU ROBLOX. I WILL
    -- RUIN YOUR REPUTATION LITTLE BITCHASS. YOU WASTED MY OWN MONEY. I WILL RUIN YOUR PLATFORM.

    ------------------------------------------------------------------------------------------------

    local robloxreturn2 = "You are back huh? okay, i will do it again, if you really want it"
    local return2broken = "ROBLOX, YOU REALLY THOUGHT YOU WERE SLICK? WELL I DESTROYED YOU AGAIN."

    error(robloxreturn2)
    print("I'm sorry, but ill come back")
    error(return2broken)